### ISSUE TITLE
some users don't have access to all slash commands

### ISSUE THREAD

**Issue by esmanning** [reminder-bot/reminder-rs#11]
I'm in a server that uses reminder-bot. While some users are able to use all of the new slash commands, at least two of us (including me) only have access to: clock, dashboard, dm allow, dm block, donate, help, info, timezone, and webhook. These are the only ones that show in the menu when I type in the /, and if I try to use a different one it just doesn't do anything. 
<img width="763" alt="Screen Shot 2022-09-05 at 11 54 35 AM" src="https://user-images.githubusercontent.com/15826763/188485334-7cfdc54a-9591-4459-85ef-ce528fae3d89.png">

I've tried this on all the platforms I have easy access to: the mac discord app, in-browser in chrome on a mac, and in the android discord app, with the same results, so it seems to be a limitation by user rather than by platform?

Since the old prefix commands are no longer working, this means we can't currently access central features like creating and viewing reminders, except through the dashboard.

**Comment by JellyWX** [comment]
Hi, you'll need an admin to go to Server Settings -> Integrations and configure permissions for the slash commands
